services:
  ai-terminal-home:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-terminal-home
    tty: true
    stdin_open: true
    environment:
      - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL:-https://api.moonshot.cn/anthropic/}
      - ANTHROPIC_AUTH_TOKEN=${ANTHROPIC_AUTH_TOKEN:-your_api_key_sk}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_api_key}
      - https_proxy=${https_proxy:-http://127.0.0.1:7890}
      - http_proxy=${http_proxy:-http://127.0.0.1:7890}
      - all_proxy=${all_proxy:-socks5://127.0.0.1:7890}
    volumes:
      - ./data:/data
    working_dir: /data
    restart: unless-stopped