# Define common configuration for the service
x-ai-terminal-common: &ai-terminal-common
  container_name: ai-terminal-home
  tty: true
  stdin_open: true
  extra_hosts:
    - "host.docker.internal:host-gateway"
  env_file:
    - .env
  volumes:
    - ./data:/data
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  working_dir: /data
  restart: unless-stopped

services:
  # Default profile: build from source
  ai-terminal-home:
    <<: *ai-terminal-common
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["build"]

  # Pull from Docker Hub
  ai-terminal-home-pull:
    <<: *ai-terminal-common
    image: xmx0632/ai-terminal-home:${VERSION:-latest}
    # 优先使用本地镜像
    pull_policy: if_not_present
    profiles: ["pull"]